# Service definitions
parameters:

services:
    aureka_vb.login_listener:
        class: Aureka\VBBundle\Event\Listener\LoginListener
        factory_class: Aureka\VBBundle\Factory\ServicesFactory
        factory_method: createLogin
        arguments: ['@aureka_vb.configuration', '@request_stack']
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onUserLogin }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    aureka_vb.logout_handler:
        class: Aureka\VBBundle\Handler\LogoutHandler
        factory_class: Aureka\VBBundle\Factory\ServicesFactory
        factory_method: createLogout
        arguments: ['@aureka_vb.configuration', '@request_stack']
