# Service definitions
parameters:

services:
    aureka_vb.users:
        class: Aureka\VBBundle\VBUsers
        arguments: ['@request_stack']

    aureka_vb.login_listener:
        class: Aureka\VBBundle\Event\Listener\LoginListener
        arguments: ['@aureka_vb.users']
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onUserLogin }
