# Service definitions
parameters:
    aureka_vb.cookie_prefix: ''
    aureka_vb.db_prefix: 'vb3_'
    aureka_vb.ip_check: 1
    aureka_vb.database: []

services:
    aureka_vb.login_listener:
        class: Aureka\VBBundle\Event\Listener\LoginListener
        factory_class: Aureka\VBBundle\Event\Listener\LoginListener
        factory_method: createFor
        arguments: ['@aureka_vb.configuration', '@request_stack']
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onUserLogin }
